
***NOTE: Messages are organized per cpu in separate sections below.


**********************************
*  Message file output, cpu #1   *
**********************************


 STEP 1  ORIGIN 0.0000


**********************************
*  Message file output, cpu #2   *
**********************************


**********************************
*  Message file output, cpu #3   *
**********************************


**********************************
*  Message file output, cpu #4   *
**********************************

